blank_issues_enabled: false
contact_links:
  - name: 💡 Ideas and Feature requests
    url: https://github.com/netizen-experience/utils/discussions/categories/ideas
    about: Discuss and propose new features or improvements
  - name: 🙋 Get Help and Technical Support
    url: https://github.com/netizen-experience/utils/discussions
    about: Ask and answer questions in the GitHub discussions page
